name: CI
on:
  - push
  - pull_request

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        # LTS (v1.10.7), latest stable, nightly
        version:
          - '1.10.7'
          - '1'
          - 'nightly'
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        arch:
          - x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      - name: Cache Julia packages
        uses: julia-actions/cache@v1

      - name: Build Julia package
        uses: julia-actions/julia-buildpkg@v1

      - name: Run tests
        uses: julia-actions/julia-runtest@v1

      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: lcov.info